### PR TITLE
Add openSUSE instructions

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by sentriz** [comment]
cool! thank you for packaging this :)

**Comment by sentriz** [comment]
PS i see that builds fail for Leap. so i've updated `meson_version` because i don't think i'm using anything required by the old version
also made another release because of #3

**Comment by jubalh** [comment]
Cool, thanks for notifying! Will update it later :)

**Comment by jubalh** [comment]
Actually dont see another release yet :D

**Comment by sentriz** [comment]
ugh forgot to `push --tags` again 😀

**Comment by jubalh** [comment]
Although unpopular in sway related projects and I have to ask everywhere explicitly: A Changelog would be a nice thing to have :)

**Comment by sentriz** [comment]
good idea. ill do it next time

**Pull request merged**
